### PR TITLE
Add Default Menu Items

### PR DESCRIPTION
**Pull request by bswinnerton**
This aims to resolve https://github.com/bswinnerton/github.lbaction/issues/22.

github-launchbar

Unfortunately the [Suggestions Script](https://developer.obdev.at/launchbar-developer-documentation/#/action-script-types) format added in this pull request adds a regression to any function that was relying on `LaunchBar.executeAppleScript('tell application "LaunchBar" to hide');` to automatically hide LaunchBar when the action is complete (added in bd287c4da004b16203b320497660dd2275af8c15).

The problem lies with the user input not being cleared out correctly, so the next time that LaunchBar opens, it sees the input, runs through the regex matching, and immediately re-executes. Essentially an infinite loop.

A temporary workaround is to comment out `LaunchBar.executeAppleScript('tell application "LaunchBar" to hide');` (which I've done), and gives the user an opportunity to modify the input on the second time around (only _after_ it's been re-executed a second time, though). 

I've reached out to @obdev's support to see if they have any ideas around this.

#### To Do

- [ ] Update screenshots in `README.md`

### CODE REVIEW

**Comment by jasonrudolph** [comment]
I'm really digging this update! 😻

**Comment by marcomasser** [comment]
I’m afraid I don’t quite understand the issue. I *think* I understand what you write, but I can’t see anything wrong in the attached GIF.
BTW: Why does LaunchBar go away at the end in the GIF? It looks like you press Esc twice (once to close the result item list and another time to hide LaunchBar).

Also, I tried to do the exact same thing you did in the GIF and I get the exact same result. I tried commit https://github.com/bswinnerton/github.lbaction/pull/30/commits/998d723165797b66f0022cdd24663b97575eb721 as well as https://github.com/bswinnerton/github.lbaction/pull/30/commits/3519c164af6026857149131960810868c3601437. Can’t see any issue. Please help 🤷‍♂️

**Comment by bswinnerton** [comment]
👋 @marcomasser,

Thank you for taking a look, and being so kind to do so in pull request form 🙏.

The screenshot in the body of this pull request is the "happy path". Here's the problem that I'm running into:

github-launchbar

In this example, I'm trying to pass in a commit SHA to find the pull request that it corresponds to. Something that was introduced in #16. But ever since enabling [live feedback](https://github.com/bswinnerton/github.lbaction/pull/30/files#diff-d44cc3f554233af40ce2089d64e6306aR38), the application doesn't zero-out the contents of the LaunchBar input between executions. 

The code paths that are being executed in the screenshot are above are as so:

1. The global `run()` function is called, originally with [no input](https://github.com/bswinnerton/github.lbaction/blob/998d723165797b66f0022cdd24663b97575eb721/Contents/Scripts/default.js#L31), so the [default menu items are displayed](https://github.com/bswinnerton/github.lbaction/blob/998d723165797b66f0022cdd24663b97575eb721/Contents/Scripts/default.js#L37)
2. The user pastes in a commit SHA, which [does not match](https://github.com/bswinnerton/github.lbaction/blob/998d723165797b66f0022cdd24663b97575eb721/Contents/Scripts/default.js#L31) any of the titles of the default menu items, so [`displayMenuItemFor(input)`](https://github.com/bswinnerton/github.lbaction/blob/998d723165797b66f0022cdd24663b97575eb721/Contents/Scripts/default.js#L59) is called
3. The `displayMenuItemFor(input)` function matches the input against a series of regular expressions to see what sort of menu item should be displayed. After checking a few regular expressions, it correctly [matches the input of the commit SHA](https://github.com/bswinnerton/github.lbaction/blob/998d723165797b66f0022cdd24663b97575eb721/Contents/Scripts/default.js#L104-L110), instantiates a `Commit` object and calls `openCommitPullRequestsMenu(commit)`
4. An [API call is made](https://github.com/bswinnerton/github.lbaction/blob/1a23e78c6834575cddf65eba0c008e8e55c007e4/Contents/Scripts/default.js#L168) to determine the commit's pull requests, if only one is returned, we [open up the link](https://github.com/bswinnerton/github.lbaction/blob/1a23e78c6834575cddf65eba0c008e8e55c007e4/Contents/Scripts/default.js#L173) in the user's browser

This all works great. It's on the _next_ execution where things get a little funky.

On the second execution, the global `run()` function is called, but already has the commit SHA entered from the last time LaunchBar's GitHub action was run. This causes us to skip right to step 3, and repeat the process.

Now this, paired with `LaunchBar.executeAppleScript('tell application "LaunchBar" to hide');` (which was not enabled when I recorded the gif, gives the user no opportunity to hit escape, meaning that there's no way to clear out the contents of the user input, and makes the action unusable.

I hope this accurately explains the problem I'm facing. I think what I'm missing is a way to clear out the contents of the user's input in LaunchBar between executions when live mode is enabled.

**Comment by bswinnerton** [comment]
@marcomasser, I've figured it out! The issue was that I was calling `LaunchBar.openURL`, which doesn't play nicely with live feedback. What I've added in https://github.com/bswinnerton/github.lbaction/compare/30250dfcebcf5a7f91c686caeaf35efb207b8172...91173a7f20b4d38f1db1d6b33accef1ef6273c3c is a series of menu items that will appear so that the user can select them, instead of immediately opening the links as they type.

Thank you for the assistance ❤️ .

**Comment by marcomasser** [comment]
@bswinnerton Thanks for the thorough explanation, now the GIF matches what I understood from the text and I see what you mean. You obviously found a usable workaround by now (not opening the URL right away, but showing a result item for the commit first). This looks really nice now!

It doesn’t seem to me that there’s anything we should change on LaunchBar’s side because the new behavior feels right to me. Do you agree?

Nonetheless, this begs the question whether we should add some functionality to LaunchBar that manipulates the user’s input. I can think of two possible solutions:

- Add an Info.plist key that specifies that before the action is called, the input should be cleared. In other words: Always start the text input with the empty string.

- Allow the action’s code to actually manipulate the user’s input. This is much more involved because the action’s code would need to be run, recognize that it’s run with *an old user input*, then modify the string and run again. Also, this could lead to usability issues because the user’s input isn’t just the user’s input anymore: It could be a transformed version of the input, which may be unexpected.

Seeing as the most likely use case would be to just clear out the old input, I think the first approach would definitely be sufficient.

Sorry for hijacking this PR for my brainstorming 😇

**Comment by jasonrudolph** [comment]
swooning

**Pull request merged**
